apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | quote }}
  food: {{ .Values.favorite.food | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: "true"
  {{- end }}
{{- range .Values.fruits }}
  {{ . }}: "available"
{{- end }}
{{- range $key, $value := .Values.vegetables }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
  