apiVersion: v1
kind: Namespace
metadata:
  name: app-a

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: app-a
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 4
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        env:
        - name: APP_NGINX_API_KEY
          value: "XYZ"
