apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80 # Service Port Number
      targetPort: 80 # Continer Port Number
# Default Service Type