apiVersion: v1
kind: Pod
metadata:
  name: secret-app-pod
spec:
  volumes:
    - name: sensitive-volume
      secret:
        secretName: app-secret
  containers:
    - name: secret-app-pod
      image: busybox
      args:
        - "/bin/sh"
        - "-c"
        - "sleep 50000"
      volumeMounts:
        - name: sensitive-volume
          readOnly: true
          mountPath: "/secret-volume"