apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
    - name: app-container
      image: kriskhuslen/fortune:v1
      env:
        # Define the environment variable
        - name: INTERVAL # Variable called INTERVAL in the application # Key NAME of Environment variable
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: fortune-config
              # Specify the key associated with the value
              key: sleep-time